// File automatically generated by swift-bridge.
#include <stdbool.h>
#include <stdint.h>
typedef struct __swift_bridge__$ResolutionPathFFI {
  void *initial_expr;
  void *steps_json;
  void *result_expr;
  bool success;
} __swift_bridge__$ResolutionPathFFI;
typedef struct __swift_bridge__$Option$ResolutionPathFFI {
  bool is_some;
  __swift_bridge__$ResolutionPathFFI val;
} __swift_bridge__$Option$ResolutionPathFFI;
typedef struct __swift_bridge__$CartesianCoords2D {
  double x;
  double y;
} __swift_bridge__$CartesianCoords2D;
typedef struct __swift_bridge__$Option$CartesianCoords2D {
  bool is_some;
  __swift_bridge__$CartesianCoords2D val;
} __swift_bridge__$Option$CartesianCoords2D;
typedef struct __swift_bridge__$CartesianCoords3D {
  double x;
  double y;
  double z;
} __swift_bridge__$CartesianCoords3D;
typedef struct __swift_bridge__$Option$CartesianCoords3D {
  bool is_some;
  __swift_bridge__$CartesianCoords3D val;
} __swift_bridge__$Option$CartesianCoords3D;
typedef struct __swift_bridge__$PolarCoords {
  double r;
  double theta;
} __swift_bridge__$PolarCoords;
typedef struct __swift_bridge__$Option$PolarCoords {
  bool is_some;
  __swift_bridge__$PolarCoords val;
} __swift_bridge__$Option$PolarCoords;
typedef struct __swift_bridge__$SphericalCoords {
  double r;
  double theta;
  double phi;
} __swift_bridge__$SphericalCoords;
typedef struct __swift_bridge__$Option$SphericalCoords {
  bool is_some;
  __swift_bridge__$SphericalCoords val;
} __swift_bridge__$Option$SphericalCoords;
typedef struct __swift_bridge__$ComplexNumber {
  double real;
  double imaginary;
} __swift_bridge__$ComplexNumber;
typedef struct __swift_bridge__$Option$ComplexNumber {
  bool is_some;
  __swift_bridge__$ComplexNumber val;
} __swift_bridge__$Option$ComplexNumber;
typedef struct __swift_bridge__$DifferentiationResultFFI {
  void *original;
  void *variable;
  void *derivative;
  void *derivative_latex;
} __swift_bridge__$DifferentiationResultFFI;
typedef struct __swift_bridge__$Option$DifferentiationResultFFI {
  bool is_some;
  __swift_bridge__$DifferentiationResultFFI val;
} __swift_bridge__$Option$DifferentiationResultFFI;
typedef struct __swift_bridge__$IntegrationResultFFI {
  void *original;
  void *variable;
  void *integral;
  void *integral_latex;
  bool success;
  void *error_message;
} __swift_bridge__$IntegrationResultFFI;
typedef struct __swift_bridge__$Option$IntegrationResultFFI {
  bool is_some;
  __swift_bridge__$IntegrationResultFFI val;
} __swift_bridge__$Option$IntegrationResultFFI;
typedef struct __swift_bridge__$DefiniteIntegralResultFFI {
  void *original;
  void *variable;
  double lower_bound;
  double upper_bound;
  void *value;
  void *value_latex;
  double numeric_value;
  bool success;
  void *error_message;
} __swift_bridge__$DefiniteIntegralResultFFI;
typedef struct __swift_bridge__$Option$DefiniteIntegralResultFFI {
  bool is_some;
  __swift_bridge__$DefiniteIntegralResultFFI val;
} __swift_bridge__$Option$DefiniteIntegralResultFFI;
typedef struct __swift_bridge__$LimitResultFFI {
  void *original;
  void *variable;
  void *approaches;
  void *value;
  void *value_latex;
  double numeric_value;
  bool success;
  void *error_message;
} __swift_bridge__$LimitResultFFI;
typedef struct __swift_bridge__$Option$LimitResultFFI {
  bool is_some;
  __swift_bridge__$LimitResultFFI val;
} __swift_bridge__$Option$LimitResultFFI;
typedef struct __swift_bridge__$EvaluationResultFFI {
  void *original;
  double value;
  bool success;
  void *error_message;
} __swift_bridge__$EvaluationResultFFI;
typedef struct __swift_bridge__$Option$EvaluationResultFFI {
  bool is_some;
  __swift_bridge__$EvaluationResultFFI val;
} __swift_bridge__$Option$EvaluationResultFFI;
typedef struct __swift_bridge__$SimplificationResultFFI {
  void *original;
  void *simplified;
  void *simplified_latex;
} __swift_bridge__$SimplificationResultFFI;
typedef struct __swift_bridge__$Option$SimplificationResultFFI {
  bool is_some;
  __swift_bridge__$SimplificationResultFFI val;
} __swift_bridge__$Option$SimplificationResultFFI;
typedef struct __swift_bridge__$ODEResultFFI {
  void *equation;
  void *solution;
  void *solution_latex;
  void *ode_type;
  void *method_used;
  bool success;
  void *error_message;
} __swift_bridge__$ODEResultFFI;
typedef struct __swift_bridge__$Option$ODEResultFFI {
  bool is_some;
  __swift_bridge__$ODEResultFFI val;
} __swift_bridge__$Option$ODEResultFFI;
typedef struct __swift_bridge__$TaylorSeriesResultFFI {
  void *original;
  void *variable;
  double center;
  uint32_t order;
  void *series;
  void *series_latex;
  bool success;
  void *error_message;
} __swift_bridge__$TaylorSeriesResultFFI;
typedef struct __swift_bridge__$Option$TaylorSeriesResultFFI {
  bool is_some;
  __swift_bridge__$TaylorSeriesResultFFI val;
} __swift_bridge__$Option$TaylorSeriesResultFFI;
typedef struct __swift_bridge__$LaurentSeriesResultFFI {
  void *original;
  void *variable;
  double center;
  uint32_t neg_order;
  uint32_t pos_order;
  void *series;
  void *series_latex;
  bool success;
  void *error_message;
} __swift_bridge__$LaurentSeriesResultFFI;
typedef struct __swift_bridge__$Option$LaurentSeriesResultFFI {
  bool is_some;
  __swift_bridge__$LaurentSeriesResultFFI val;
} __swift_bridge__$Option$LaurentSeriesResultFFI;
typedef struct __swift_bridge__$AsymptoticSeriesResultFFI {
  void *original;
  void *variable;
  void *direction;
  uint32_t num_terms;
  void *series;
  void *series_latex;
  bool success;
  void *error_message;
} __swift_bridge__$AsymptoticSeriesResultFFI;
typedef struct __swift_bridge__$Option$AsymptoticSeriesResultFFI {
  bool is_some;
  __swift_bridge__$AsymptoticSeriesResultFFI val;
} __swift_bridge__$Option$AsymptoticSeriesResultFFI;
typedef struct __swift_bridge__$SpecialFunctionResultFFI {
  void *value;
  void *value_latex;
  double numeric_value;
  void *derivation_steps;
  bool success;
  void *error_message;
} __swift_bridge__$SpecialFunctionResultFFI;
typedef struct __swift_bridge__$Option$SpecialFunctionResultFFI {
  bool is_some;
  __swift_bridge__$SpecialFunctionResultFFI val;
} __swift_bridge__$Option$SpecialFunctionResultFFI;
typedef struct __swift_bridge__$PrecisionEvaluationResultFFI {
  void *original;
  double value;
  void *value_string;
  void *precision_mode;
  void *rounding_mode;
  bool success;
  void *error_message;
} __swift_bridge__$PrecisionEvaluationResultFFI;
typedef struct __swift_bridge__$Option$PrecisionEvaluationResultFFI {
  bool is_some;
  __swift_bridge__$PrecisionEvaluationResultFFI val;
} __swift_bridge__$Option$PrecisionEvaluationResultFFI;
typedef struct __swift_bridge__$FourierSeriesResultFFI {
  void *original;
  void *variable;
  uint32_t num_terms;
  double period;
  void *a_coefficients_json;
  void *b_coefficients_json;
  void *series;
  void *series_latex;
  bool success;
  void *error_message;
} __swift_bridge__$FourierSeriesResultFFI;
typedef struct __swift_bridge__$Option$FourierSeriesResultFFI {
  bool is_some;
  __swift_bridge__$FourierSeriesResultFFI val;
} __swift_bridge__$Option$FourierSeriesResultFFI;
struct __private__ResultPtrAndPtr
__swift_bridge__$parse_equation_ffi(struct RustStr input);
struct __private__ResultPtrAndPtr
__swift_bridge__$parse_expression_ffi(struct RustStr input);
struct __swift_bridge__$ODEResultFFI
__swift_bridge__$solve_ode_ffi(struct RustStr equation,
                               struct RustStr dependent_var,
                               struct RustStr independent_var);
struct __swift_bridge__$ODEResultFFI __swift_bridge__$solve_ode_ivp_ffi(
    struct RustStr equation, struct RustStr dependent_var,
    struct RustStr independent_var, struct RustStr initial_conditions_json);
struct __swift_bridge__$ResultODEResultFFIAndString
__swift_bridge__$solve_second_order_ode_ffi(struct RustStr coefficients_json,
                                            struct RustStr forcing_fn);
struct __swift_bridge__$ResultODEResultFFIAndString
__swift_bridge__$solve_higher_order_ode_ffi(struct RustStr coefficients_json);
struct __private__ResultPtrAndPtr
__swift_bridge__$rk4_solve_ffi(struct RustStr equation, struct RustStr variable,
                               double x0, double y0, double x_end,
                               uint32_t steps);
struct __private__ResultPtrAndPtr
__swift_bridge__$solve_equation_ffi(struct RustStr equation,
                                    struct RustStr variable);
struct __swift_bridge__$ResultResolutionPathFFIAndString
__swift_bridge__$solve_with_values_ffi(struct RustStr equation,
                                       struct RustStr variable,
                                       struct RustStr known_values_json);
struct __swift_bridge__$ResultF64AndString
__swift_bridge__$solve_numerically_ffi(struct RustStr equation,
                                       struct RustStr variable,
                                       double initial_guess);
struct __swift_bridge__$PolarCoords
__swift_bridge__$cartesian_to_polar_ffi(double x, double y);
struct __swift_bridge__$CartesianCoords2D
__swift_bridge__$polar_to_cartesian_ffi(double r, double theta);
struct __swift_bridge__$SphericalCoords
__swift_bridge__$cartesian_to_spherical_ffi(double x, double y, double z);
struct __swift_bridge__$CartesianCoords3D
__swift_bridge__$spherical_to_cartesian_ffi(double r, double theta, double phi);
struct __swift_bridge__$ComplexNumber
__swift_bridge__$complex_add_ffi(double a_re, double a_im, double b_re,
                                 double b_im);
struct __swift_bridge__$ComplexNumber
__swift_bridge__$complex_multiply_ffi(double a_re, double a_im, double b_re,
                                      double b_im);
struct __swift_bridge__$PolarCoords
__swift_bridge__$complex_to_polar_ffi(double re, double im);
struct __swift_bridge__$ComplexNumber
__swift_bridge__$complex_power_ffi(double re, double im, double n);
struct __private__ResultPtrAndPtr
__swift_bridge__$parse_latex_ffi(struct RustStr input);
struct __private__ResultPtrAndPtr
__swift_bridge__$parse_latex_to_latex_ffi(struct RustStr input);
struct __private__ResultPtrAndPtr
__swift_bridge__$to_latex_ffi(struct RustStr expression);
struct __swift_bridge__$ResultDifferentiationResultFFIAndString
__swift_bridge__$differentiate_ffi(struct RustStr expression,
                                   struct RustStr variable);
struct __swift_bridge__$ResultDifferentiationResultFFIAndString
__swift_bridge__$differentiate_n_ffi(struct RustStr expression,
                                     struct RustStr variable, uint32_t n);
struct __private__ResultPtrAndPtr
__swift_bridge__$gradient_ffi(struct RustStr expression,
                              struct RustStr variables_json);
struct __swift_bridge__$ResultIntegrationResultFFIAndString
__swift_bridge__$integrate_ffi(struct RustStr expression,
                               struct RustStr variable);
struct __swift_bridge__$ResultDefiniteIntegralResultFFIAndString
__swift_bridge__$definite_integral_ffi(struct RustStr expression,
                                       struct RustStr variable, double lower,
                                       double upper);
struct __swift_bridge__$ResultLimitResultFFIAndString
__swift_bridge__$limit_ffi(struct RustStr expression, struct RustStr variable,
                           double approaches);
struct __swift_bridge__$ResultLimitResultFFIAndString
__swift_bridge__$limit_infinity_ffi(struct RustStr expression,
                                    struct RustStr variable);
struct __swift_bridge__$ResultEvaluationResultFFIAndString
__swift_bridge__$evaluate_ffi(struct RustStr expression,
                              struct RustStr values_json);
struct __swift_bridge__$ResultSimplificationResultFFIAndString
__swift_bridge__$simplify_ffi(struct RustStr expression);
struct __swift_bridge__$ResultSimplificationResultFFIAndString
__swift_bridge__$simplify_trig_ffi(struct RustStr expression);
struct __private__ResultPtrAndPtr
__swift_bridge__$simplify_trig_with_steps_ffi(struct RustStr expression);
struct __private__ResultPtrAndPtr
__swift_bridge__$solve_system_ffi(struct RustStr equations_json);
struct __private__ResultPtrAndPtr
__swift_bridge__$solve_inequality_ffi(struct RustStr inequality,
                                      struct RustStr variable);
struct __private__ResultPtrAndPtr
__swift_bridge__$partial_fractions_ffi(struct RustStr numerator,
                                       struct RustStr denominator,
                                       struct RustStr variable);
struct __private__ResultPtrAndPtr
__swift_bridge__$solve_equation_system_ffi(struct RustStr equations_json,
                                           struct RustStr known_values_json,
                                           struct RustStr targets_json);
struct __swift_bridge__$ResultTaylorSeriesResultFFIAndString
__swift_bridge__$taylor_series_ffi(struct RustStr expression,
                                   struct RustStr variable, double center,
                                   uint32_t order);
struct __swift_bridge__$ResultTaylorSeriesResultFFIAndString
__swift_bridge__$maclaurin_series_ffi(struct RustStr expression,
                                      struct RustStr variable, uint32_t order);
struct __swift_bridge__$ResultLaurentSeriesResultFFIAndString
__swift_bridge__$laurent_series_ffi(struct RustStr expression,
                                    struct RustStr variable, double center,
                                    uint32_t neg_order, uint32_t pos_order);
struct __swift_bridge__$ResultAsymptoticSeriesResultFFIAndString
__swift_bridge__$asymptotic_series_ffi(struct RustStr expression,
                                       struct RustStr variable,
                                       struct RustStr direction,
                                       uint32_t num_terms);
struct __swift_bridge__$ResultTaylorSeriesResultFFIAndString
__swift_bridge__$compose_series_ffi(struct RustStr outer, struct RustStr inner,
                                    struct RustStr variable, uint32_t order);
struct __swift_bridge__$ResultTaylorSeriesResultFFIAndString
__swift_bridge__$reversion_series_ffi(struct RustStr expression,
                                      struct RustStr variable, uint32_t order);
struct __swift_bridge__$ResultSpecialFunctionResultFFIAndString
__swift_bridge__$gamma_ffi(double x);
struct __swift_bridge__$ResultSpecialFunctionResultFFIAndString
__swift_bridge__$erf_ffi(double x);
struct __swift_bridge__$ResultSpecialFunctionResultFFIAndString
__swift_bridge__$beta_ffi(double a, double b);
struct __swift_bridge__$ResultSpecialFunctionResultFFIAndString
__swift_bridge__$erfc_ffi(double x);
struct __swift_bridge__$ResultPrecisionEvaluationResultFFIAndString
__swift_bridge__$evaluate_with_precision_ffi(struct RustStr expression,
                                             struct RustStr values_json,
                                             struct RustStr mode,
                                             uint32_t precision,
                                             struct RustStr rounding);
struct __private__ResultPtrAndPtr
__swift_bridge__$optimize_for_manual_computation_ffi(struct RustStr expression);
struct __private__ResultPtrAndPtr
__swift_bridge__$small_angle_approximation_ffi(struct RustStr expression,
                                               struct RustStr variable,
                                               double threshold);
struct __swift_bridge__$ResultFourierSeriesResultFFIAndString
__swift_bridge__$fourier_series_ffi(struct RustStr expression,
                                    struct RustStr variable, uint32_t num_terms,
                                    double period);
struct __swift_bridge__$CartesianCoords2D
__swift_bridge__$translate_2d_ffi(double x, double y, double dx, double dy);
struct __swift_bridge__$CartesianCoords2D
__swift_bridge__$rotate_2d_ffi(double x, double y, double theta);
struct __swift_bridge__$CartesianCoords2D
__swift_bridge__$scale_2d_ffi(double x, double y, double sx, double sy);
struct __private__ResultPtrAndPtr
__swift_bridge__$complex_nth_roots_ffi(double re, double im, int32_t n);
struct __swift_bridge__$ResultF64AndString
__swift_bridge__$convert_units_ffi(double value, struct RustStr from_unit,
                                   struct RustStr to_unit);
struct __private__ResultPtrAndPtr
__swift_bridge__$parse_latex_calculus_ffi(struct RustStr input);
typedef enum __swift_bridge__$ResultODEResultFFIAndString$Tag {
  __swift_bridge__$ResultODEResultFFIAndString$ResultOk,
  __swift_bridge__$ResultODEResultFFIAndString$ResultErr
} __swift_bridge__$ResultODEResultFFIAndString$Tag;
union __swift_bridge__$ResultODEResultFFIAndString$Fields {
  struct __swift_bridge__$ODEResultFFI ok;
  void *err;
};
typedef struct __swift_bridge__$ResultODEResultFFIAndString {
  __swift_bridge__$ResultODEResultFFIAndString$Tag tag;
  union __swift_bridge__$ResultODEResultFFIAndString$Fields payload;
} __swift_bridge__$ResultODEResultFFIAndString;
typedef enum __swift_bridge__$ResultResolutionPathFFIAndString$Tag {
  __swift_bridge__$ResultResolutionPathFFIAndString$ResultOk,
  __swift_bridge__$ResultResolutionPathFFIAndString$ResultErr
} __swift_bridge__$ResultResolutionPathFFIAndString$Tag;
union __swift_bridge__$ResultResolutionPathFFIAndString$Fields {
  struct __swift_bridge__$ResolutionPathFFI ok;
  void *err;
};
typedef struct __swift_bridge__$ResultResolutionPathFFIAndString {
  __swift_bridge__$ResultResolutionPathFFIAndString$Tag tag;
  union __swift_bridge__$ResultResolutionPathFFIAndString$Fields payload;
} __swift_bridge__$ResultResolutionPathFFIAndString;
typedef enum __swift_bridge__$ResultF64AndString$Tag {
  __swift_bridge__$ResultF64AndString$ResultOk,
  __swift_bridge__$ResultF64AndString$ResultErr
} __swift_bridge__$ResultF64AndString$Tag;
union __swift_bridge__$ResultF64AndString$Fields {
  double ok;
  void *err;
};
typedef struct __swift_bridge__$ResultF64AndString {
  __swift_bridge__$ResultF64AndString$Tag tag;
  union __swift_bridge__$ResultF64AndString$Fields payload;
} __swift_bridge__$ResultF64AndString;
typedef enum __swift_bridge__$ResultDifferentiationResultFFIAndString$Tag {
  __swift_bridge__$ResultDifferentiationResultFFIAndString$ResultOk,
  __swift_bridge__$ResultDifferentiationResultFFIAndString$ResultErr
} __swift_bridge__$ResultDifferentiationResultFFIAndString$Tag;
union __swift_bridge__$ResultDifferentiationResultFFIAndString$Fields {
  struct __swift_bridge__$DifferentiationResultFFI ok;
  void *err;
};
typedef struct __swift_bridge__$ResultDifferentiationResultFFIAndString {
  __swift_bridge__$ResultDifferentiationResultFFIAndString$Tag tag;
  union __swift_bridge__$ResultDifferentiationResultFFIAndString$Fields payload;
} __swift_bridge__$ResultDifferentiationResultFFIAndString;
typedef enum __swift_bridge__$ResultIntegrationResultFFIAndString$Tag {
  __swift_bridge__$ResultIntegrationResultFFIAndString$ResultOk,
  __swift_bridge__$ResultIntegrationResultFFIAndString$ResultErr
} __swift_bridge__$ResultIntegrationResultFFIAndString$Tag;
union __swift_bridge__$ResultIntegrationResultFFIAndString$Fields {
  struct __swift_bridge__$IntegrationResultFFI ok;
  void *err;
};
typedef struct __swift_bridge__$ResultIntegrationResultFFIAndString {
  __swift_bridge__$ResultIntegrationResultFFIAndString$Tag tag;
  union __swift_bridge__$ResultIntegrationResultFFIAndString$Fields payload;
} __swift_bridge__$ResultIntegrationResultFFIAndString;
typedef enum __swift_bridge__$ResultDefiniteIntegralResultFFIAndString$Tag {
  __swift_bridge__$ResultDefiniteIntegralResultFFIAndString$ResultOk,
  __swift_bridge__$ResultDefiniteIntegralResultFFIAndString$ResultErr
} __swift_bridge__$ResultDefiniteIntegralResultFFIAndString$Tag;
union __swift_bridge__$ResultDefiniteIntegralResultFFIAndString$Fields {
  struct __swift_bridge__$DefiniteIntegralResultFFI ok;
  void *err;
};
typedef struct __swift_bridge__$ResultDefiniteIntegralResultFFIAndString {
  __swift_bridge__$ResultDefiniteIntegralResultFFIAndString$Tag tag;
  union __swift_bridge__$ResultDefiniteIntegralResultFFIAndString$Fields
      payload;
} __swift_bridge__$ResultDefiniteIntegralResultFFIAndString;
typedef enum __swift_bridge__$ResultLimitResultFFIAndString$Tag {
  __swift_bridge__$ResultLimitResultFFIAndString$ResultOk,
  __swift_bridge__$ResultLimitResultFFIAndString$ResultErr
} __swift_bridge__$ResultLimitResultFFIAndString$Tag;
union __swift_bridge__$ResultLimitResultFFIAndString$Fields {
  struct __swift_bridge__$LimitResultFFI ok;
  void *err;
};
typedef struct __swift_bridge__$ResultLimitResultFFIAndString {
  __swift_bridge__$ResultLimitResultFFIAndString$Tag tag;
  union __swift_bridge__$ResultLimitResultFFIAndString$Fields payload;
} __swift_bridge__$ResultLimitResultFFIAndString;
typedef enum __swift_bridge__$ResultEvaluationResultFFIAndString$Tag {
  __swift_bridge__$ResultEvaluationResultFFIAndString$ResultOk,
  __swift_bridge__$ResultEvaluationResultFFIAndString$ResultErr
} __swift_bridge__$ResultEvaluationResultFFIAndString$Tag;
union __swift_bridge__$ResultEvaluationResultFFIAndString$Fields {
  struct __swift_bridge__$EvaluationResultFFI ok;
  void *err;
};
typedef struct __swift_bridge__$ResultEvaluationResultFFIAndString {
  __swift_bridge__$ResultEvaluationResultFFIAndString$Tag tag;
  union __swift_bridge__$ResultEvaluationResultFFIAndString$Fields payload;
} __swift_bridge__$ResultEvaluationResultFFIAndString;
typedef enum __swift_bridge__$ResultSimplificationResultFFIAndString$Tag {
  __swift_bridge__$ResultSimplificationResultFFIAndString$ResultOk,
  __swift_bridge__$ResultSimplificationResultFFIAndString$ResultErr
} __swift_bridge__$ResultSimplificationResultFFIAndString$Tag;
union __swift_bridge__$ResultSimplificationResultFFIAndString$Fields {
  struct __swift_bridge__$SimplificationResultFFI ok;
  void *err;
};
typedef struct __swift_bridge__$ResultSimplificationResultFFIAndString {
  __swift_bridge__$ResultSimplificationResultFFIAndString$Tag tag;
  union __swift_bridge__$ResultSimplificationResultFFIAndString$Fields payload;
} __swift_bridge__$ResultSimplificationResultFFIAndString;
typedef enum __swift_bridge__$ResultTaylorSeriesResultFFIAndString$Tag {
  __swift_bridge__$ResultTaylorSeriesResultFFIAndString$ResultOk,
  __swift_bridge__$ResultTaylorSeriesResultFFIAndString$ResultErr
} __swift_bridge__$ResultTaylorSeriesResultFFIAndString$Tag;
union __swift_bridge__$ResultTaylorSeriesResultFFIAndString$Fields {
  struct __swift_bridge__$TaylorSeriesResultFFI ok;
  void *err;
};
typedef struct __swift_bridge__$ResultTaylorSeriesResultFFIAndString {
  __swift_bridge__$ResultTaylorSeriesResultFFIAndString$Tag tag;
  union __swift_bridge__$ResultTaylorSeriesResultFFIAndString$Fields payload;
} __swift_bridge__$ResultTaylorSeriesResultFFIAndString;
typedef enum __swift_bridge__$ResultLaurentSeriesResultFFIAndString$Tag {
  __swift_bridge__$ResultLaurentSeriesResultFFIAndString$ResultOk,
  __swift_bridge__$ResultLaurentSeriesResultFFIAndString$ResultErr
} __swift_bridge__$ResultLaurentSeriesResultFFIAndString$Tag;
union __swift_bridge__$ResultLaurentSeriesResultFFIAndString$Fields {
  struct __swift_bridge__$LaurentSeriesResultFFI ok;
  void *err;
};
typedef struct __swift_bridge__$ResultLaurentSeriesResultFFIAndString {
  __swift_bridge__$ResultLaurentSeriesResultFFIAndString$Tag tag;
  union __swift_bridge__$ResultLaurentSeriesResultFFIAndString$Fields payload;
} __swift_bridge__$ResultLaurentSeriesResultFFIAndString;
typedef enum __swift_bridge__$ResultAsymptoticSeriesResultFFIAndString$Tag {
  __swift_bridge__$ResultAsymptoticSeriesResultFFIAndString$ResultOk,
  __swift_bridge__$ResultAsymptoticSeriesResultFFIAndString$ResultErr
} __swift_bridge__$ResultAsymptoticSeriesResultFFIAndString$Tag;
union __swift_bridge__$ResultAsymptoticSeriesResultFFIAndString$Fields {
  struct __swift_bridge__$AsymptoticSeriesResultFFI ok;
  void *err;
};
typedef struct __swift_bridge__$ResultAsymptoticSeriesResultFFIAndString {
  __swift_bridge__$ResultAsymptoticSeriesResultFFIAndString$Tag tag;
  union __swift_bridge__$ResultAsymptoticSeriesResultFFIAndString$Fields
      payload;
} __swift_bridge__$ResultAsymptoticSeriesResultFFIAndString;
typedef enum __swift_bridge__$ResultSpecialFunctionResultFFIAndString$Tag {
  __swift_bridge__$ResultSpecialFunctionResultFFIAndString$ResultOk,
  __swift_bridge__$ResultSpecialFunctionResultFFIAndString$ResultErr
} __swift_bridge__$ResultSpecialFunctionResultFFIAndString$Tag;
union __swift_bridge__$ResultSpecialFunctionResultFFIAndString$Fields {
  struct __swift_bridge__$SpecialFunctionResultFFI ok;
  void *err;
};
typedef struct __swift_bridge__$ResultSpecialFunctionResultFFIAndString {
  __swift_bridge__$ResultSpecialFunctionResultFFIAndString$Tag tag;
  union __swift_bridge__$ResultSpecialFunctionResultFFIAndString$Fields payload;
} __swift_bridge__$ResultSpecialFunctionResultFFIAndString;
typedef enum __swift_bridge__$ResultPrecisionEvaluationResultFFIAndString$Tag {
  __swift_bridge__$ResultPrecisionEvaluationResultFFIAndString$ResultOk,
  __swift_bridge__$ResultPrecisionEvaluationResultFFIAndString$ResultErr
} __swift_bridge__$ResultPrecisionEvaluationResultFFIAndString$Tag;
union __swift_bridge__$ResultPrecisionEvaluationResultFFIAndString$Fields {
  struct __swift_bridge__$PrecisionEvaluationResultFFI ok;
  void *err;
};
typedef struct __swift_bridge__$ResultPrecisionEvaluationResultFFIAndString {
  __swift_bridge__$ResultPrecisionEvaluationResultFFIAndString$Tag tag;
  union __swift_bridge__$ResultPrecisionEvaluationResultFFIAndString$Fields
      payload;
} __swift_bridge__$ResultPrecisionEvaluationResultFFIAndString;
typedef enum __swift_bridge__$ResultFourierSeriesResultFFIAndString$Tag {
  __swift_bridge__$ResultFourierSeriesResultFFIAndString$ResultOk,
  __swift_bridge__$ResultFourierSeriesResultFFIAndString$ResultErr
} __swift_bridge__$ResultFourierSeriesResultFFIAndString$Tag;
union __swift_bridge__$ResultFourierSeriesResultFFIAndString$Fields {
  struct __swift_bridge__$FourierSeriesResultFFI ok;
  void *err;
};
typedef struct __swift_bridge__$ResultFourierSeriesResultFFIAndString {
  __swift_bridge__$ResultFourierSeriesResultFFIAndString$Tag tag;
  union __swift_bridge__$ResultFourierSeriesResultFFIAndString$Fields payload;
} __swift_bridge__$ResultFourierSeriesResultFFIAndString;
